language: julia
os:
    - linux
julia:
    - release
    - nightly
    - 0.5.2
after_success:
    - julia -e 'Pkg.add("Coverage")'
    - julia -e 'cd(Pkg.dir("AbaqusReader")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("AbaqusReader")); using Documenter; include(joinpath("docs", "make.jl"))'
