language: julia
os:
    - linux
julia:
    - 0.7
    - 1.0
    - nightly
matrix:
    allow_failures:
        - julia: 1.0
        - julia: nightly
before_script:
    - julia --color=yes -e 'using Pkg; Pkg.clone("https://github.com/JuliaFEM/PkgTestSuite.jl.git")'
    - julia --color=yes -e 'using PkgTestSuite; init()'
script:
    - julia --color=yes -e 'using PkgTestSuite; test()'
after_success:
    - julia --color=yes -e 'using PkgTestSuite; deploy()'
