name = "AbaqusReader"
uuid = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.2.6"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
