name = "AbaqusReader"
uuid = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
version = "0.2.6"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Coverage = "1.8.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
