site_name: AbaqusReader.jl
repo_url: https://github.com/JuliaFEM/AbaqusReader.jl.git
site_description: Parse ABAQUS .inp file
site_author: ahojukka5

theme: readthedocs

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - assets/mathjaxhelper.js

markdown_extensions:
    - extra
    - tables
    - fenced_code
    - footnotes
    - mdx_math:
        enable_dollar_delimiter: True

docs_dir: 'build'

pages:
    - Home: index.md
